// /lib/badgesData.js or /data/badgesData.js

/**
 * Mock data for all user badges.
 * To be replaced with an API call in the future.
 */
export const badges = [
  {
    id: 1,
    category: "Mammals",
    icon: "🦁",
    totalSpecies: 286,
    discoveredSpecies: 100,
    discovered: [
      "Malayan Tiger",
      "Asian Elephant",
      "Sun Bear",
      "Proboscis Monkey",
      "Clouded Leopard",
      "Binturong",
      "Pangolin",
      "Slow Loris",
      "Dusky Leaf Monkey",
      "Long-tailed Macaque",
    ],
    undiscovered: [
      "Malayan Tapir",
      "Banteng",
      "Sambar Deer",
      "Wild Boar",
      "Mousedeer",
      "Flying Squirrel",
      "Moonrat",
      "Otter Civet",
    ],
  },
  {
    id: 2,
    category: "Birds",
    icon: "🦜",
    totalSpecies: 742,
    discoveredSpecies: 520,
    discovered: [
      "Rhinoceros Hornbill",
      "Oriental Pied Hornbill",
      "Blue-throated Bee-eater",
      "Kingfisher",
      "White-bellied Sea Eagle",
      "Brahminy Kite",
      "Oriental Dwarf Kingfisher",
      "Greater Racket-tailed Drongo",
    ],
    undiscovered: [
      "Storm's Stork",
      "Masked Finfoot",
      "Great Argus",
      "Crested Fireback",
    ],
  },
  {
    id: 3,
    category: "Reptiles",
    icon: "🦎",
    totalSpecies: 567,
    discoveredSpecies: 85,
    discovered: [
      "Reticulated Python",
      "King Cobra",
      "Tokay Gecko",
      "Water Monitor",
      "Saltwater Crocodile",
      "Malayan Box Turtle",
    ],
    undiscovered: [
      "Painted Terrapin",
      "Leatherback Sea Turtle",
      "Green Sea Turtle",
      "Hawksbill Turtle",
      "Flying Dragon",
      "Mangrove Snake",
    ],
  },
  {
    id: 4,
    category: "Amphibians",
    icon: "🐸",
    totalSpecies: 242,
    discoveredSpecies: 40,
    discovered: [
      "Wallace's Flying Frog",
      "Giant River Toad",
      "File-eared Tree Frog",
      "Harlequin Tree Frog",
    ],
    undiscovered: [
      "Bornean Flat-headed Frog",
      "Kinabalu Horned Frog",
      "Mossy Frog",
      "Malaysian Horned Frog",
    ],
  },
  {
    id: 5,
    category: "Fish",
    icon: "🐠",
    totalSpecies: 1951,
    discoveredSpecies: 195,
    discovered: [
      "Arowana",
      "Giant Gourami",
      "Clown Loach",
      "Betta Fish",
      "Rasbora",
      "Mahseer",
      "Snakehead",
    ],
    undiscovered: ["Hampala Barb", "Kelah", "River Catfish", "Archerfish"],
  },
  {
    id: 6,
    category: "Insects",
    icon: "🦋",
    totalSpecies: 150000,
    discoveredSpecies: 1200,
    discovered: [
      "Rajah Brooke's Birdwing",
      "Atlas Moth",
      "Orchid Mantis",
      "Giant Forest Ant",
      "Lantern Bug",
      "Jewel Beetle",
    ],
    undiscovered: [
      "Bornean Moon Moth",
      "Giant Stick Insect",
      "Rhinoceros Beetle",
      "Cicada",
    ],
  },
  {
    id: 7,
    category: "Arachnids",
    icon: "🕷️",
    totalSpecies: 950,
    discoveredSpecies: 45,
    discovered: [
      "Tarantula",
      "Jumping Spider",
      "Giant Forest Scorpion",
      "Whip Spider",
    ],
    undiscovered: [
      "Trapdoor Spider",
      "Lynx Spider",
      "Crab Spider",
      "Orb Weaver",
    ],
  },
  {
    id: 8,
    category: "Mollusks",
    icon: "🐚",
    totalSpecies: 378,
    discoveredSpecies: 12,
    discovered: ["Giant African Snail", "Tree Snail", "Freshwater Clam"],
    undiscovered: ["Sea Slug", "Conch", "Cowrie", "Octopus", "Nautilus"],
  },
  {
    id: 9,
    category: "Plants",
    icon: "🌱",
    totalSpecies: 100,
    discoveredSpecies: 4,
    discovered: ["Apple Tree", "Orange Tree", "Coconut Tree", "Banana Tree"],
    undiscovered: ["Durian Tree"],
  },
];